language: cpp

compiler:
- gcc

os:
- linux


install:
    - sudo apt-get update
    - sudo apt-get install libeigen3-dev
    - git clone https://github.com/coin-or/qpOASES.git
    - cd qpOASES 
    - mkdir build && cd build 
    - cmake .. -DCMAKE_CXX_FLAGS=-fPIC
    - sudo make install
    - cd ../../ 

script: 
    - cmake ./cpp
        
